name: tow_management_system_ui

description: "Tow management system user interface."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  intl: ^0.20.2
  amplify_flutter: ^2.7.0
  amplify_auth_cognito: ^2.7.0
  amplify_authenticator: ^2.3.8
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/amplify_configuration.json

